### ISSUE TITLE
百度贴吧网页端使用的是Angular是么？

### ISSUE THREAD

**Issue by YuyangHYY** [luckyadam/resume#1]
请问下，项目经验部分提到的贴吧页面等开发使用Angular，是指百度贴吧么？
如果是，可不可以了解下当时百度贴吧网页端使用的是angualr哪个版本呢？

**Comment by luckyadam** [comment]
贴吧内部系统用的angular，线上没有

**Comment by YuyangHYY** [comment]
哦 所以你是做内部系统开发及维护是吧
方便的话可以交流一下 微信：544612210
